name: mangacafe
description: mangacafe is a place for manga lovers.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  carousel_slider: ^4.0.0
  cupertino_icons: ^1.0.2
  dio: ^4.0.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  intro_slider: ^3.0.3
  shared_preferences: ^2.0.12
  shared_preferences_web: ^2.0.3
  webview_flutter: ^3.0.0

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/cropped-logo.site_-192x192.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/pdfs/

  fonts:
    - family: BYekan
      fonts:
        - asset: assets/fonts/BYekan.ttf
